service: aws

frameworkVersion: '>=<3.15.0'

plugins:
  - serverless-offline
  - serverless-step-functions
  - '@vibou/serverless-step-functions-offline'

provider:
  name: aws
  stage: ${opt:stage, 'local'}
  runtime: nodejs14.x
  region: eu-west-1
  memorySize: 128
  timeout: 3

serverless-offline:
  noPrependStageInUrl: true
  httpPort: 3001

step-functions-offline:
  lambdaEndpoint: http://localhost:3002

custom:
  stepFunctionsOffline:
    Producer: producer
    Reducer: reducer
    MappingFunction: mapper

functions: 
  ${file(functions.yml)}

stepFunctions:
  stateMachines:
    map_reduce:
      definition: 
        Comment: 'Export a PDF document for the given dashboard'
        StartAt: Producer
        States: ${file(states.yml)}
      
