service: ServerlessStepPlugin

frameworkVersion: '>=<2.0.0'

plugins:
   - serverless-step-functions
   - serverless-step-functions-offline


provider:
  name: aws
  runtime: nodejs14.x
  cfLogs: true
  region: eu-west-1
  memorySize: 128
  timeout: 3

custom:
  stepFunctionsOffline:
      FirstLambda: firstLambda

functions:
  - ${file(functions.yml)}

stepFunctions:
  stateMachines:
    foo:
      definition:
        Comment: "An example of the Amazon States Language using wait states"
        StartAt: FirstLambda
        States: ${file(states.yml)}